behaviors:
  SideScroller:
    trainer_type: ppo
    time_horizon: 128
    max_steps: 1.0e7
    threaded: true
    hyperparameters:
      batch_size: 128
      beta: 0.01
      buffer_size: 2048
      epsilon: 0.2
      lambd: 0.95
      learning_rate: 0.003
      num_epoch: 3
    network_settings:
      num_layers: 2
      normalize: false
      hidden_units: 512
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        strength: 0.02
        gamma: 0.99
        network_settings:
          hidden_units: 256
      gail:
        strength: 0.1
        gamma: 0.99
        demo_path: Demos/SideScroller2_1.demo
    behavioral_cloning:
      demo_path: Demos/SideScroller2_1.demo
      strength: 0.3
      steps: 150000
      num_epoch: 3
      ##Test20 3 epochs
      #Test28 gail strength 0.3, num epochs of BC and PPO = 5
      #Test 34 gail strenth 0.1 BC strength 0.3